# Generates lua_embed.h from the addon sources so the executable can install
# the game-side scripts without shipping a folder alongside it.
#
# Invoked as:
#   cmake -DADDON_DIR=... -DOUT=... -P GenerateLuaEmbed.cmake

if(NOT DEFINED ADDON_DIR OR NOT DEFINED OUT)
    message(FATAL_ERROR "GenerateLuaEmbed.cmake requires -DADDON_DIR and -DOUT")
endif()

set(_files
    "scripts/vscripts/game/gameinit.lua"
    "scripts/vscripts/mods/init/psvr2_haptics.lua"
    "scripts/vscripts/psvr2_haptics/core.lua"
)

set(_out "// Generated by GenerateLuaEmbed.cmake - do not edit.\n")
string(APPEND _out "#pragma once\n\n")
string(APPEND _out "namespace psvr2 {\n\n")
set(_sc ";")
string(APPEND _out "struct EmbeddedFile { const char* relativePath${_sc} const char* contents${_sc} }${_sc}\n\n")
string(APPEND _out "inline const EmbeddedFile kAddonFiles[] = {\n")

foreach(_f IN LISTS _files)
    set(_full "${ADDON_DIR}/${_f}")
    if(NOT EXISTS "${_full}")
        message(FATAL_ERROR "Missing addon source: ${_full}")
    endif()
    file(READ "${_full}" _content)
    # A raw string literal keeps the Lua byte-for-byte identical. The delimiter
    # is chosen so it cannot appear in Lua source.
    string(APPEND _out "    { \"${_f}\", R\"PSVR2LUA(${_content})PSVR2LUA\" },\n")
endforeach()

string(APPEND _out "}${_sc}\n\n")
string(APPEND _out "} // namespace psvr2\n")

# Only rewrite when the content actually changes, so the build does not relink
# on every configure.
set(_existing "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _existing)
endif()
if(NOT _existing STREQUAL _out)
    file(WRITE "${OUT}" "${_out}")
    message(STATUS "Generated ${OUT}")
endif()
